apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  replicas: 2

  template:
    spec:
      volumes:
        - name: varnish-config-volume
          configMap:
            name: varnish-config

      containers:
        - name: alod-ch
          image: "docker.io/zazukoians/varnish:5.2.1"
          imagePullPolicy: IfNotPresent

          env:
            - name: VCL_CONFIG
              value: /config/default.vcl

          volumeMounts:
            - name: varnish-config-volume
              mountPath: /config

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 150m
              memory: 100Mi

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # This makes sure the pods are not all scheduled on the same node
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels: {}
                topologyKey: "kubernetes.io/hostname"
